// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRyRwf-2M0KSUakjUybusGbEq2rSXxkNw',
    appId: '1:37402483502:web:e1e81b80e966d85d2ab8bf',
    messagingSenderId: '37402483502',
    projectId: 'fasum-app-3006b',
    authDomain: 'fasum-app-3006b.firebaseapp.com',
    storageBucket: 'fasum-app-3006b.firebasestorage.app',
    measurementId: 'G-YWYW97FLN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE8sLHo-_b0gVgjNhVQfwmEfMtkKRLHjw',
    appId: '1:37402483502:android:ec6b72670b04d4042ab8bf',
    messagingSenderId: '37402483502',
    projectId: 'fasum-app-3006b',
    storageBucket: 'fasum-app-3006b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRyRwf-2M0KSUakjUybusGbEq2rSXxkNw',
    appId: '1:37402483502:web:951d3ea46f2628ec2ab8bf',
    messagingSenderId: '37402483502',
    projectId: 'fasum-app-3006b',
    authDomain: 'fasum-app-3006b.firebaseapp.com',
    storageBucket: 'fasum-app-3006b.firebasestorage.app',
    measurementId: 'G-25QMR3JX2M',
  );
}
